import type { Metadata } from 'next'
import './globals.css'
import Navbar from '@/components/Main/Navigation/Navbar'
import Footer from '@/components/Main/Footer/Footer'
import { ConfigProvider } from 'antd'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ConfigProvider
        theme={{
          token: {
            colorPrimary: '#00b96b',
            colorBgContainer: '#2D2F36',
          },
          components: {
            InputNumber: {
              activeBg: '#2D2F36'
            }
          }

        }}
      >
        <body className="min-h-screen flex flex-col">
          <Navbar />
          <main className="flex-grow">
            {children}
          </main>
          <Footer />
        </body>
      </ConfigProvider>
    </html>
  )
}