import type { Metadata } from 'next'
import './globals.css'
import Navbar from '@/components/Main/Navigation/Navbar'
import Footer from '@/components/Main/Footer/Footer'
import { Providers } from '@/components/Providers'
import { Suspense } from 'react'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <Suspense fallback={<div>NACITAM SE...</div>}> */}
      <body className="min-h-screen flex flex-col bg-slate-950">
        <Providers>
          <Navbar />
          <main className="flex-grow">
            {children}
          </main>
        </Providers>
        <Footer />
      </body>
      {/* </Suspense> */}
    </html>
  )
}