import type { Metadata } from 'next'
import './globals.css'
import Navbar from '@/components/Main/Navigation/Navbar'
import Footer from '@/components/Main/Footer/Footer'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />

        {children}</body>

      <Footer />
    </html>
  )
}
